//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace CCN.TraceSystem.Model
{
    /// <summary>
    /// 企业性质
    /// </summary>
    public class Dict_Enterprise_Property
    {
        /// <summary>
        /// 企业性质ID
        /// </summary>
        [Key]
        public virtual string Property_ID
        {
            get;
            set;
        }

        /// <summary>
        /// 企业性质名称
        /// </summary>

        public virtual string Property_Name
        {
            get;
            set;
        }

    }
}

