//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;


namespace CCN.TraceSystem.Model
{
    /// <summary>
    /// 企业联系方式
    /// </summary>
    public class EnterPrise_Contact
    {
        public virtual string Contact_Man
        {
            get;
            set;
        }

        /// <summary>
        /// 联系地址
        /// </summary>
        public virtual string Contact_Address
        {
            get;
            set;
        }

        /// <summary>
        /// 企业电话
        /// </summary>
        public virtual string EnterPrise_Phone
        {
            get;
            set;
        }

        /// <summary>
        /// 企业邮箱
        /// </summary>
        public virtual string EnterPrise_Email
        {
            get;
            set;
        }

        /// <summary>
        /// 企业传真
        /// </summary>
        public virtual string EnterPrise_Fax
        {
            get;
            set;
        }

        /// <summary>
        /// 手机
        /// </summary>
        public virtual string Contact_TelePhone
        {
            get;
            set;
        }

        /// <summary>
        /// 邮政编码
        /// </summary>
        public virtual string Post_Code
        {
            get;
            set;
        }

        ///// <summary>
        ///// 联系方式ID
        ///// </summary>
        //public virtual string Contact_ID
        //{
        //    get;
        //    set;
        //}

    }


}