//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Entity;
using System.Data.EntityModel;
using System.ComponentModel.DataAnnotations;


namespace CCN.TraceSystem.Model
{

    /// <summary>
    /// 企业基础信息
    /// </summary>
    /// <remarks>企业基础信息</remarks>
    public class ENTERPRISEIFO
    {

        public ENTERPRISEIFO() {
            this.EnterPrise_Contact = new EnterPrise_Contact();
        }

        /// <summary>
        /// 组织结构代码
        /// </summary>
        public virtual string ORGANIZATIONCODEID
        {
            get;
            set;
        }

        /// <summary>
        /// 行政区域
        /// </summary>
        public virtual string AREAID
        {
            get;
            set;
        }

        /// <summary>
        /// 企业名称
        /// </summary>
        public virtual string ENTERPRISE_NAME
        {
            get;
            set;
        }

        /// <summary>
        /// 企业编号
        /// </summary>
        public virtual string ENTERPRISE_ID
        {
            get;
            set;
        }

        /// <summary>
        /// 注册地址
        /// </summary>
        public virtual string REG_ADDRESS
        {
            get;
            set;
        }

        /// <summary>
        /// 企业性质
        /// </summary>
        public virtual string ENTERPRISE_PROPERTY_ID
        {
            get;
            set;
        }

        /// <summary>
        /// 企业法人
        /// </summary>
        public virtual string BUSSINESS_ENTITY
        {
            get;
            set;
        }

        /// <summary>
        /// 生产产品
        /// </summary>
        public virtual string PRODUCTION_PRODUCTS
        {
            get;
            set;
        }

        /// <summary>
        /// 注册资本
        /// </summary>
        public virtual string REGISTERED_CAPITAL
        {
            get;
            set;
        }

        /// <summary>
        /// 企业人数
        /// </summary>
        public virtual string EMPLOYEES_COUNTS
        {
            get;
            set;
        }

        /// <summary>
        /// 控制行版本,防止并发
        /// </summary>
        public virtual byte[] ROWVERSION
        {
            get;
            set;
        }
        //public virtual Organization  Organization 
        //{
        //    get;
        //    set;
        //}

        //public virtual Dict_AreaInfo AreaInfo
        //{
        //    get;
        //    set;
        //}

        //public virtual Dict_Enterprise_Property Dict_Enterprise_Property
        //{
        //    get;
        //    set;
        //}

        public virtual EnterPrise_Contact EnterPrise_Contact
        {
            get;
            set;
        }

        //public virtual IndustryType_Desc IndustryType_Desc
        //{
        //    get;
        //    set;
        //}

        /// <summary>
        /// 新增一个企业信息
        /// </summary>
        public virtual void CreateNewEnterPriseInfo()
        {
            //throw new System.NotImplementedException();
        }

    }
}

