//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;


namespace CCN.TraceSystem.Model
{
    /// <summary>
    /// 所属行业
    /// </summary>
    public class IndustryType
    {
        /// <summary>
        /// 行业ID
        /// </summary>
        [Key]
        public virtual string IndustryType_ID
        {
            get;
            set;
        }

        /// <summary>
        /// 行业名称
        /// </summary>
        public virtual string IndustryType_Name
        {
            get;
            set;
        }

    }


}