//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;


namespace CCN.TraceSystem.Model
{
    /// <summary>
    /// 所属行业描述
    /// </summary>
    public class IndustryType_Desc
    {
        /// <summary>
        /// 行业ID
        /// </summary>
        public virtual string IndustryType_ID
        {
            get;
            set;
        }

        /// <summary>
        /// 经营范围
        /// </summary>
        public virtual string Business_Scope
        {
            get;
            set;
        }

        /// <summary>
        /// 主要品牌
        /// </summary>
        public virtual string Major_Brand
        {
            get;
            set;
        }

        /// <summary>
        /// 主要产品
        /// </summary>
        public virtual string Production_Products
        {
            get;
            set;
        }

        /// <summary>
        /// 行业描述ID
        /// </summary>
        [Key]
        public virtual string IndustryType_Desc_ID
        {
            get;
            set;
        }

        public virtual IndustryType IndustryType
        {
            get;
            set;
        }

    }
}

